### ISSUE TITLE
Not clear what repo should be used 

### ISSUE THREAD

**Issue by d-d-d-dalia** [learn-co-curriculum/rails-static-request-readme#10]
says to run rails server, but not clear from which directory. references config/routes.rb which is not in the master code.

**Comment by hansenjl** [comment]
Agreed - I've had students get confused because there's no repo to use.

**Comment by AudTheCodeWitch** [comment]
As a student, this readme is frustrating. It reads like a code-along, but I have nothing to actually look at/do.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
