### ISSUE TITLE
no files

### ISSUE THREAD

**Issue by codingkasia** [learn-co-curriculum/rails-static-request-readme#11]
it looks like this is more like a lab/code along not readme since it asks to open config/routes.rb file and add the following route inside of the draw block:

get 'about', to: 'static#about' 

but there are no files to fork to follow along.

**Comment by drakeltheryuujin** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
