### ISSUE TITLE
Rails Server Bug

### ISSUE THREAD

**Issue by doosemavis** [learn-co-curriculum/rails-static-request-readme#22]
Hi there, I had to add the following items to my VSCode from the `rails-static-request-readme` lab for the server to boot up properly in this lab.  Wanted to let you all know about it! 

**Inside:**  `app/assets`

**Added this folder:** `config`

**In config folder, added this file:** `manifest.js` 

**In manifest.js, added this code:** 

`//= link_tree ../images`
`//= link_directory ../javascripts .js`
`//= link_directory ../stylesheets .css`

**I was receiving this error before I added that code:** 

=> Booting Puma
=> Rails 5.0.7.1 application starting in development on http://localhost:3000
=> Run `rails server -h` for more startup options
Exiting
Traceback (most recent call last):
	34: from bin/rails:4:in `<main>'
	33: from bin/rails:4:in `require'
	32: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/commands.rb:18:in `<top (required)>'
	31: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	30: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/commands/commands_tasks.rb:85:in `server'
	29: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/commands/commands_tasks.rb:85:in `tap'
	28: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/commands/commands_tasks.rb:90:in `block in server'
	27: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/commands/server.rb:102:in `start'
	26: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/commands/server.rb:148:in `log_to_stdout'
	25: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	24: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/commands/server.rb:84:in `app'
	23: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	22: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	21: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	20: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	19: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	18: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	17: from /Users/Moose/Development/Flatiron/labs/rails-static-request-readme-onl01-seng-ft-090820/config.ru:3:in `block in <main>'
	16: from /Users/Moose/Development/Flatiron/labs/rails-static-request-readme-onl01-seng-ft-090820/config.ru:3:in `require'
	15: from /Users/Moose/Development/Flatiron/labs/rails-static-request-readme-onl01-seng-ft-090820/config/environment.rb:5:in `<top (required)>'
	14: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/application.rb:352:in `initialize!'
	13: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/initializable.rb:54:in `run_initializers'
	12: from /Users/Moose/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:205:in `tsort_each'
	11: from /Users/Moose/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:226:in `tsort_each'
	10: from /Users/Moose/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each_strongly_connected_component'
	 9: from /Users/Moose/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `call'
	 8: from /Users/Moose/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:347:in `each'
	 7: from /Users/Moose/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 6: from /Users/Moose/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 5: from /Users/Moose/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 4: from /Users/Moose/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/tsort.rb:228:in `block in tsort_each'
	 3: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/initializable.rb:55:in `block in run_initializers'
	 2: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/initializable.rb:30:in `run'
	 1: from /Users/Moose/.rvm/gems/ruby-2.6.1/gems/railties-5.0.7.1/lib/rails/initializable.rb:30:in `instance_exec'
/Users/Moose/.rvm/gems/ruby-2.6.1/gems/sprockets-rails-3.2.2/lib/sprockets/railtie.rb:106:in `block in <class:Railtie>': Expected to find a manifest file in `app/assets/config/manifest.js` (Sprockets::Railtie::ManifestNeededError)
But did not, please create this file and use it to link any assets that need
to be rendered by your app:

Example:
  //= link_tree ../images
  //= link_directory ../javascripts .js
  //= link_directory ../stylesheets .css
and restart your server

For more information see: https://github.com/rails/sprockets/blob/070fc01947c111d35bb4c836e9bb71962a8e0595/UPGRADING.md#manifestjs

**Comment by lizbur10** [comment]
Hi Moose! Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙

**Comment by doosemavis** [comment]
Hi Liz!


Thanks for following up on this, so glad that others won’t have to endure that troubleshooting issue.  Haha, definitely through me for a loop that’s for sure.  But just means I learned something new!   

Happy that I could help :) 

Have a great day! 


Sincerely,
Moose
